### ISSUE TITLE
Tab Preferences dialog starts too small

### ISSUE THREAD

**Issue by AustinShalit** [wpilibsuite/shuffleboard#124]
It starts with scroll bars now.  It should not.

**Comment by AustinShalit** [comment]
Image for context: 
![untitled](https://user-images.githubusercontent.com/3799260/29183674-73b6f5de-7db8-11e7-82f4-ec8d0f23e2b0.jpeg)

**Comment by nightpool** [comment]
set fitToHeight=true from CSS

**Comment by nightpool** [comment]
Oh, jesus, this was a hairy bug. Adding fitToHeight didn't do anything. 

To make a long story short, it turns out that PropertySheet doesn't handle setting padding correctly, at *all*. If you set any padding on PropertySheet, it ignores that completely when doing layout calculations.

But what was setting the padding in the first place? We never set padding on PropertySheet, and neither does ControlsFX (or they would have found this bug right away). Well, it turns out that, by default, Dialog panes set padding on their content. So by overriding that style, I got rid of the bug. It looks kinda terrible though, so I might just end up wrapping the PropertySheet in a BorderPane or something.
