### ISSUE TITLE
Consider making constructors private when possible and exposing static factory methods

### ISSUE THREAD

**Issue by JLLeitschuh** [wpilibsuite/shuffleboard#166]
When you expose an API, you will inevitably make mistakes or need to make design changes.

Before making your API public you should consider trying to minimize the number of constructors you expose as part of your published API.

## Reasoning

http://jtechies.blogspot.com/2012/07/item-1-consider-static-factory-methods.html

If you expose a constructor you can't then change the type to being an interface or an abstract class without breaking your API consumers.
If you expose a static factory method if you convert the type to an interface all of your API consumers won't be impacted by the change.

Using static factory methods also gives you the flexibility to do additional checks before/after the object is constructed. For example Guava's `ImmutableList.copyOf` first checks if the list being passed is already an `ImmutableList` type and doesn't copy it if it is.

**Comment by nightpool** [comment]
As is this issue is too broad to implement. Can you identify some specific examples where you think this is a problem in the codebase, and the changes you would make to them? Keep in mind that any components designed to be used from FXML need to use constructors and that classes with few if any consumers probably don't need to be changed.
