### ISSUE TITLE
Simple Color Changes

### ISSUE THREAD

**Issue by allengregoryiv** [wpilibsuite/shuffleboard#296]
Have a menu to specify the 2-3 main theme colors without having to generate a theme. Teams would like to be able to theme it close to their team colors.

Also, in the Dark theme the toggle button changes between grey and red which is weird since red is false for the Boolean box but true for the toggle button.

**Comment by SamCarlberg** [comment]
The recent changes to themes (#349) that make it possible to have CSS files in ~/Shufleboard/themes is an acceptable resolution in my opinion. ([Documentation](https://github.com/wpilibsuite/shuffleboard/wiki/Custom-themes))

I don't think that adding a tool to shuffleboard for this would be a good solution, since it would be bound too closely to the bundled themes without necessarily working on custom themes.
