### ISSUE TITLE
Need to make videos work with record/playback

### ISSUE THREAD

**Issue by bradamiller** [wpilibsuite/shuffleboard#300]
Currently videos aren't replayed in record/playback

**Comment by SamCarlberg** [comment]
To clarify, camera streams have code for recording and playback that is currently disabled because:

1. Video files aren't properly encoded. Appear to have no frame count? The frames _are_ written, however
2. Due to recordings being saved periodically, duplicate frames are appended to the video files instead of just appending the new frames. This doesn't impact playback, but makes the video files look weird when viewing in a 3rd party app like VLC.
