### ISSUE TITLE
UI is too big

### ISSUE THREAD

**Issue by AustinShalit** [wpilibsuite/shuffleboard#38]
The UI is too large and less information can be presented in a single view.  See the attached image of 2 identically sized windows.  On the left is shuffleboard.  On the right is SmartDashboard.

![untitled](https://user-images.githubusercontent.com/3799260/28378130-f69f7f54-6c63-11e7-9937-cbe5f855fb8e.jpeg)

**Comment by SamCarlberg** [comment]
This is intentional to reduce visual clutter. We're going to allow the tile sizes to be changed by users on a per-tab basis, but the default is large to avoid having scores of components that make it impossible to find what you're looking for

**Comment by bradamiller** [comment]
Personally I prefer the smaller non-grid layout although I understand that the other layout managers are in the plan and am giving this the benefit of the doubt because of that future feature. So maybe we can bump up the priority for alternate layouts so we can see what it will really look like and we'll have time to comment.
