### ISSUE TITLE
Small numbers not being updated

### ISSUE THREAD

**Issue by bartkerfeld** [wpilibsuite/shuffleboard#630]
**Describe the bug**  
When comparing the results of `SmartDashboard.putNumber` and `System.out.println`, I noticed was not always seeing the same value for the same variable. It appears to be an issue of handling small numbers. When looking at the Outline Viewer, it is clear that the appropriate number is stored in Network Tables, however, Shuffleboard is not displaying it correctly. [This YouTube video](https://youtu.be/-RlSNMu6diE) show an example. 

**To Reproduce**  
1. Send a small value (on the order or 10E-5) and observe it not being updated on the Dashboard.

**Expected behavior**  
Shuffleboard should always displays values matching the Outline Viewer.

**Screenshots**  
See YouTube video above.

**Desktop (please complete the following information):**
 - OS: Windows
 - Will Update Java and Shuffleboard version later: They are whatever are included in the last 2019 WPILIB update, but am away from workstation to pull exact numbers.

**Additional context**  
None

**Comment by PeterJohnson** [comment]
I think the root cause is that NumberField requires numbers be in standard decimal form (e.g. 1.234) here: https://github.com/wpilibsuite/shuffleboard/blob/master/api/src/main/java/edu/wpi/first/shuffleboard/api/components/NumberField.java#L11

but Double.toString() is used here to output the number: https://github.com/wpilibsuite/shuffleboard/blob/master/api/src/main/java/edu/wpi/first/shuffleboard/api/components/AbstractNumberField.java#L47

and Double.toString() uses exponential notation (1.234e-5) when values get below 10^-3.  https://docs.oracle.com/javase/7/docs/api/java/lang/Double.html#toString(double)

So I think the fix is to either change from using toString to instead always format in decimal notation, or allow exponential number formats.
